/**
 * GENERATED from tokens.json by scripts/build-tokens.ts. Do not edit.
 *
 * Makes token names checkable at compile time: `token('--accent')` is valid,
 * `token('--acent')` is a type error rather than a silently dead CSS variable.
 */

export type TokenName =
  | '--paper'
  | '--paper-raised'
  | '--paper-deep'
  | '--ink'
  | '--ink-soft'
  | '--muted'
  | '--faint'
  | '--line'
  | '--fill'
  | '--accent'
  | '--accent-soft'
  | '--accent-text'
  | '--invert'
  | '--statement-soft'
  | '--on-invert'
  | '--on-invert-dim'
  | '--line-invert'
  | '--brand-nonbiri'
  | '--brand-nonbiri-text'
  | '--brand-suji'
  | '--brand-suji-text'
  | '--brand-gokaku'
  | '--brand-gokaku-text'
  | '--r-none'
  | '--r-sm'
  | '--r-md'
  | '--r-lg'
  | '--r-xl'
  | '--r-pill'
  | '--s-xs'
  | '--s-sm'
  | '--s-md'
  | '--s-lg'
  | '--s-xl'
  | '--s-2xl'
  | '--s-3xl'
  | '--s-4xl'
  | '--font-sans'
  | '--font-display'
  | '--font-serif'
  | '--font-cjk'
  | '--font-mincho'
  | '--font-mono'
  | '--t-caption'
  | '--t-micro'
  | '--t-body'
  | '--t-body-large'
  | '--t-title'
  | '--t-headline'
  | '--t-large-title'
  | '--t-display'
  | '--t-hero'
  | '--t-hero-xl'
  | '--t-mega'
  | '--lh-tight'
  | '--lh-snug'
  | '--lh-normal'
  | '--lh-relaxed'
  | '--tr-tight'
  | '--tr-normal'
  | '--tr-wide'
  | '--tr-eyebrow'
  | '--tr-label'
  | '--tr-vertical'
  | '--fast'
  | '--normal'
  | '--slow'
  | '--ease'
  | '--ease-in-out'
  | '--measure'
  | '--content-width'
  | '--prose-width'
  | '--tap'
  ;

export type BrandName = 'nonbiri' | 'suji' | 'gokaku';

/** `var(--…)` for a known token. Unknown names fail to compile. */
export declare function token(name: TokenName): string;
